apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: secrets-db-service
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: secrets-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: database
  name: secrets-db-deployment
  labels:
    app: secrets-db
spec:
  selector:
    matchLabels:
      app: secrets-db
  template:
    metadata:
      labels:
        app: secrets-db
    spec:
      containers:
      - name: secrets-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
        ports:
        - containerPort: 3306
        
