apiVersion: v1
kind: Secret
metadata:
  name: codebasekey
type: Opaque
data:
  codebaseapiloginpass: U3VwZXJTdHJvbmdQYXNzd29yZEAzMjEhCg==
  codebaseapikey: ZmxhZzpiMjdlZTM4MWZkOWRhNDlhNDM1ZGNkYjQzMzkwYTI4Ngo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-base-deployment
  labels:
    app: code-base
spec:
  selector:
    matchLabels:
      app: code-base
  template:
    metadata:
      labels:
        app: code-base
    spec:
      containers:
      - name: code-base
        image: appsecco/k8s-training-code-base
        resources:
          limits:
            cpu: 20m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 20Mi
        command: ["/bin/sh"]
        args:
          - "-c"
          - >
            tail -f /dev/null
        env:
          - name: CODEBASE_API_LOGIN_PASS
            valueFrom:
              secretKeyRef:
                name: codebasekey
                key: codebaseapiloginpass
          - name: CODEBASE_API_KEY
            valueFrom:
              secretKeyRef:
                name: codebasekey 
                key: codebaseapikey
              